
-- Usuarios de Administración
CREATE USER 'canaima'@'localhost' IDENTIFIED BY  'T3MxmFKhtU6WnKnQ';
GRANT SELECT , 
INSERT ,
UPDATE ,
DELETE ,
LOCK TABLES ,
EXECUTE ON `canaima` . * TO  'canaima'@'localhost' 
WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 
MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0 ;

